//! First-launch migration: convert legacy `~/.config/zed/settings.json`
//! (JSONC) and `~/.config/codon/keymap.toml` (TOML) into a unified
//! `~/.config/codon/codon.toml`. Idempotent — runs only when the unified
//! file is absent.
//!
//! The source files are left in place with a `# DEPRECATED` header
//! prepended so users can revert by deleting `codon.toml`. JSONC comments
//! on Zed settings do not survive the JSON → TOML round-trip; if the user
//! cares about a comment, the source file is still on disk for reference.

use std::{fs, io, path::PathBuf};

use anyhow::{Context as _, Result};
use serde_json::Value;

const ZED_SETTINGS_HEADER: &str = "// DEPRECATED: superseded by ~/.config/codon/codon.toml.\n\
                                   // Delete that file to restore reading this one.\n\n";
const KEYMAP_TOML_HEADER: &str = "# DEPRECATED: superseded by ~/.config/codon/codon.toml.\n\
                                  # Delete that file to restore reading this one.\n\n";
const CODON_TOML_HEADER: &str = "# Generated by codon's first-launch migration from\n\
                                 #   ~/.config/zed/settings.json and ~/.config/codon/keymap.toml.\n\
                                 # The `[settings.*]` and `[bindings.*]` shapes are documented in\n\
                                 # crates/codon-config/README.md.\n\n";

/// Stub written when codon launches for the first time on a clean install
/// (no legacy `settings.json` or `keymap.toml` to migrate from). Both
/// sections are present but empty so the user has a discoverable
/// starting point — press cmd-k F1 inside codon to inspect the live
/// keymap, edit this file to override.
const CODON_TOML_STUB: &str = "# Codon — user configuration.\n\
                               #\n\
                               # This file was created automatically on first launch. Anything you\n\
                               # leave out keeps codon's embedded defaults. Live-reload is on —\n\
                               # saves take effect without a restart.\n\
                               #\n\
                               # See assets/config/codon.example.toml in the codon source tree for\n\
                               # an annotated example covering every setting and binding. Press\n\
                               # cmd-k F1 from inside codon to see every active key binding.\n\n\
                               [settings]\n\
                               # Zed-equivalent settings (theme, fonts, editor, terminal, languages).\n\
                               # Example:\n\
                               #\n\
                               #   buffer_font_size = 14\n\
                               #   [settings.theme]\n\
                               #   mode = \"system\"\n\
                               #   light = \"One Light\"\n\
                               #   dark = \"One Dark\"\n\n\
                               [bindings.global]\n\
                               # Override default codon keybindings here. Anything not listed falls\n\
                               # through to the embedded default keymap.\n";

#[derive(Debug, PartialEq, Eq)]
pub enum MigrationOutcome {
    /// codon.toml already existed; nothing to do.
    Already,
    /// codon.toml was just written from one or more legacy files.
    Migrated {
        from_zed_settings: bool,
        from_codon_keymap: bool,
    },
    /// Clean install (no codon.toml, no legacy files). A discoverable stub
    /// was written so the user has an editable starting point.
    Scaffolded,
}

/// Run the one-shot migration if the unified file is missing. Safe to call
/// on every codon startup.
pub fn migrate_if_needed() -> Result<MigrationOutcome> {
    let Some(codon_dir) = crate::codon_config_dir() else {
        return Ok(MigrationOutcome::Scaffolded);
    };
    let unified = codon_dir.join("codon.toml");
    if unified.exists() {
        return Ok(MigrationOutcome::Already);
    }

    // The legacy Zed settings still live wherever the platform default
    // puts them (`~/Library/Application Support/Zed/settings.json` on
    // macOS) — only codon's own files moved to `~/.config/codon`.
    let zed_settings = dirs::config_dir()
        .map(|d| d.join("zed").join("settings.json"))
        .unwrap_or_default();
    let legacy_keymap = codon_dir.join("keymap.toml");

    let zed_doc = read_jsonc_if_present(&zed_settings)?;
    let keymap_doc = read_toml_if_present(&legacy_keymap)?;

    if zed_doc.is_none() && keymap_doc.is_none() {
        if let Some(parent) = unified.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("creating {} for codon.toml", parent.display()))?;
        }
        fs::write(&unified, CODON_TOML_STUB)
            .with_context(|| format!("writing {}", unified.display()))?;
        return Ok(MigrationOutcome::Scaffolded);
    }

    let mut output = String::from(CODON_TOML_HEADER);

    if let Some(json) = &zed_doc {
        let toml_value = json_to_toml(json);
        if let toml::Value::Table(table) = toml_value
            && !table.is_empty()
        {
            // Wrap under [settings] by constructing a parent table.
            let mut wrapper = toml::value::Table::new();
            wrapper.insert("settings".to_string(), toml::Value::Table(table));
            let serialised = toml::to_string_pretty(&wrapper)
                .context("serialising migrated settings to TOML")?;
            output.push_str(&serialised);
            output.push('\n');
        }
    }

    if let Some(keymap) = &keymap_doc {
        // The legacy keymap.toml already has [bindings.*] at top level —
        // we emit it verbatim so user formatting is preserved on this side
        // of the migration (we round-trip the parsed value, but stable
        // serialisation is close enough that hand-formatted keymaps stay
        // readable).
        let serialised =
            toml::to_string_pretty(keymap).context("serialising migrated keymap to TOML")?;
        output.push_str(&serialised);
        output.push('\n');
    }

    if let Some(parent) = unified.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating {} for codon.toml", parent.display()))?;
    }
    fs::write(&unified, &output).with_context(|| format!("writing {}", unified.display()))?;

    if zed_doc.is_some() {
        prepend_header(&zed_settings, ZED_SETTINGS_HEADER)?;
    }
    if keymap_doc.is_some() {
        prepend_header(&legacy_keymap, KEYMAP_TOML_HEADER)?;
    }

    Ok(MigrationOutcome::Migrated {
        from_zed_settings: zed_doc.is_some(),
        from_codon_keymap: keymap_doc.is_some(),
    })
}

/// Recursive JSON → TOML translator. The inverse of
/// `toml_to_json::translate`. Drops `null` values entirely (TOML has no
/// equivalent representation). Floats / ints round-trip; very large u64
/// values that don't fit in i64 are converted to floats (TOML's only
/// integer type is i64).
pub fn json_to_toml(value: &Value) -> toml::Value {
    match value {
        Value::Null => toml::Value::String(String::new()),
        Value::Bool(b) => toml::Value::Boolean(*b),
        Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                toml::Value::Integer(i)
            } else if let Some(f) = n.as_f64() {
                toml::Value::Float(f)
            } else {
                toml::Value::Float(n.as_f64().unwrap_or(0.0))
            }
        }
        Value::String(s) => toml::Value::String(s.clone()),
        Value::Array(items) => toml::Value::Array(items.iter().map(json_to_toml).collect()),
        Value::Object(map) => {
            let mut table = toml::value::Table::new();
            for (key, child) in map {
                // Drop nulls — TOML can't represent them without inventing
                // a sentinel, and Zed treats missing keys as defaults.
                if matches!(child, Value::Null) {
                    continue;
                }
                table.insert(key.clone(), json_to_toml(child));
            }
            toml::Value::Table(table)
        }
    }
}

fn read_jsonc_if_present(path: &PathBuf) -> Result<Option<Value>> {
    match fs::read_to_string(path) {
        Ok(content) => {
            // Strip a leading deprecation header if a previous failed
            // migration left one — keeps re-runs idempotent.
            let stripped = strip_deprecation_header(&content);
            let value: Value = settings_json::parse_json_with_comments(stripped)
                .with_context(|| format!("parsing {}", path.display()))?;
            Ok(Some(value))
        }
        Err(err) if err.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(err).with_context(|| format!("reading {}", path.display())),
    }
}

fn read_toml_if_present(path: &PathBuf) -> Result<Option<toml::Value>> {
    match fs::read_to_string(path) {
        Ok(content) => {
            let stripped = strip_deprecation_header(&content);
            let value: toml::Value = stripped
                .parse()
                .with_context(|| format!("parsing {}", path.display()))?;
            Ok(Some(value))
        }
        Err(err) if err.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(err).with_context(|| format!("reading {}", path.display())),
    }
}

fn strip_deprecation_header(content: &str) -> &str {
    content
        .strip_prefix(ZED_SETTINGS_HEADER)
        .or_else(|| content.strip_prefix(KEYMAP_TOML_HEADER))
        .unwrap_or(content)
}

fn prepend_header(path: &PathBuf, header: &str) -> Result<()> {
    let existing =
        fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    if existing.starts_with(header) {
        return Ok(()); // already annotated
    }
    let new_content = format!("{header}{existing}");
    fs::write(path, new_content).with_context(|| format!("writing {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn primitives_round_trip() {
        let json = json!({
            "s": "hello",
            "i": 42,
            "f": 3.5,
            "b": true,
            "n": null,
        });
        let toml_val = json_to_toml(&json);
        let table = toml_val.as_table().unwrap();
        assert_eq!(table["s"].as_str(), Some("hello"));
        assert_eq!(table["i"].as_integer(), Some(42));
        assert!((table["f"].as_float().unwrap() - 3.5).abs() < 1e-6);
        assert_eq!(table["b"].as_bool(), Some(true));
        // Null entries are dropped.
        assert!(!table.contains_key("n"));
    }

    #[test]
    fn nested_objects_translate() {
        let json = json!({
            "theme": { "mode": "system", "light": "One Light" },
        });
        let toml_val = json_to_toml(&json);
        let theme = &toml_val.as_table().unwrap()["theme"].as_table().unwrap();
        assert_eq!(theme["mode"].as_str(), Some("system"));
        assert_eq!(theme["light"].as_str(), Some("One Light"));
    }

    #[test]
    fn array_of_objects_translate() {
        let json = json!({
            "keymap": [
                {"context": "Editor"},
                {"context": "Terminal"},
            ],
        });
        let toml_val = json_to_toml(&json);
        let keymap = toml_val.as_table().unwrap()["keymap"].as_array().unwrap();
        assert_eq!(
            keymap[0].as_table().unwrap()["context"].as_str(),
            Some("Editor")
        );
        assert_eq!(
            keymap[1].as_table().unwrap()["context"].as_str(),
            Some("Terminal")
        );
    }
}
