[package]
name = "file-manager"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true

[dependencies]
anyhow.workspace = true
codon-config.workspace = true
codon-mode.workspace = true
file_icons.workspace = true
flate2.workspace = true
fs.workspace = true
git.workspace = true
gpui.workspace = true
image.workspace = true
log.workspace = true
menu.workspace = true
mime_guess.workspace = true
paths.workspace = true
project.workspace = true
schemars.workspace = true
serde.workspace = true
settings.workspace = true
tar.workspace = true
theme.workspace = true
toml.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true
zed_actions.workspace = true
zip.workspace = true
