[package]
name = "codon-config"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
path = "src/codon_config.rs"

[dependencies]
anyhow.workspace = true
dirs.workspace = true
fs.workspace = true
futures.workspace = true
gpui.workspace = true
log.workspace = true
platform_title_bar.workspace = true
serde.workspace = true
serde_json.workspace = true
settings.workspace = true
settings_json.workspace = true
toml.workspace = true
toml_edit.workspace = true
